ardupilot_default_airframe: gazebo-iris
ardupilot_dir: /home/rycker/projects/ardupilot
global_coordinates:
  altitude: 90.0
  latitude: 38.736832
  longitude: -9.137977
px4_default_airframe: gazebo-classic_iris
px4_dir: ~/src/PX4-Autopilot
